# -*- coding: utf-8 -*-
"""Rasa_Action.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZpVbutd9dR6AU2af5fkznb7bgWBo8DX
"""

from rasa_sdk import Action
from rasa_sdk.events import SlotSet

class ActionCooking(Action):
    def name(self):
        return "ActionCooking"

    def run(self, dispatcher, tracker, domain):
        if recipe:
            description = ', '.join(recipe.ingredients)
            dispatcher.utter_message(text=f"Cooking name is {recipe.title}.")
            dispatcher.utter_message(text=f"Ingredient Content is {description}")
            return [SlotSet("recipe", recipe)]
        else:
            dispatcher.utter_message(text="Sorry, I can't find Link.")
            return []